"""empty message

Revision ID: 8efeea7b84b2
Revises: 
Create Date: 2018-10-28 13:51:08.616565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8efeea7b84b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('irc_server',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('irc_server', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watcher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.Text(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('notify_via_mail', sa.Boolean(), nullable=False),
    sa.Column('notify_via_irc', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('irc_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('irc_server', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['irc_server'], ['irc_server.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('irc_preferences')
    op.drop_table('watcher')
    op.drop_table('irc_server')
    # ### end Alembic commands ###
